adminkey: adminkey
allowips:
    - 192.168.0.1/24
autoaddthreshold: -1
autoreset: ""
listenport: 8081
protectports:
    - 1080
    - 1081
ratetrigger: ""
reject: false
reverseproxysupport: false
userkey: userkey
whitelistedips:
whitelistedports:
    - 22
    - 23
